services:
  db:
    container_name: portfolio-pg
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  web:
    container_name: portfolio
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    # volumes:
    #   - .:/code
    ports:
      - "18000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy