# Generated by Django 3.2.16 on 2023-10-06 12:46

import content.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=50)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('gradyear', models.CharField(blank=True, max_length=50)),
                ('concentration', models.CharField(blank=True, max_length=50)),
                ('achievements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='portfolioOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('sitename', models.CharField(blank=True, max_length=50)),
                ('github', models.URLField(blank=True, max_length=2048)),
                ('gitea', models.URLField(blank=True, max_length=2048)),
                ('linkedin', models.URLField(blank=True, max_length=2048)),
                ('upwork', models.URLField(blank=True, max_length=2048)),
                ('resume', models.FileField(blank=True, upload_to=content.models.set_resume_filename, validators=[content.models.validate_resume_filetype])),
                ('headshot', models.ImageField(blank=True, upload_to=content.models.set_headshot_filename)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('blurb', models.CharField(max_length=150)),
                ('explevel', models.CharField(choices=[('exp', 'Expert'), ('pro', 'Proficient'), ('com', 'Competent'), ('adv', 'Advanced Beginner'), ('nov', 'Novice')], default='exp', max_length=3)),
                ('longdesc', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tagline', models.CharField(max_length=150)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('longdesc', models.TextField()),
                ('repo', models.URLField(blank=True, max_length=2048)),
                ('live', models.URLField(blank=True, max_length=2048)),
                ('promoted', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('skills', models.ManyToManyField(to='content.skill')),
            ],
        ),
    ]
