# Generated by Django 3.2.16 on 2023-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioowner',
            name='taglines',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
