# Generated by Django 3.2.16 on 2023-10-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_portfolioowner_taglines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioowner',
            name='tagline',
        ),
    ]
