x-app: &portfolio
  build:
    context: ../
    dockerfile: .devcontainer/dockerfile
  volumes:
    - ..:/code
  restart: "unless-stopped"

services:
  db:
    container_name: portfolio-pg
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  web:
    container_name: portfolio
    <<: *portfolio
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "18000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  tailwind:
    <<: *portfolio
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true