networks:
  default:
    name: dev_env_bridge
    external: true

x-app: &portfolio
  build:
    context: ../
    dockerfile: .devcontainer/dockerfile
  volumes:
    - ..:/code
  restart: "unless-stopped"

services:
  db:
    container_name: portfolio-pg
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  web:
    container_name: portfolio
    <<: *portfolio
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  tailwind:
    container_name: tailwind_watcher
    <<: *portfolio
    command: sh -c "sudo chmod -R 777 /code/.devcontainer/data/db && tailwindcss -c /code/.devcontainer/tailwind/tailwind.config.js -i /code/.devcontainer/tailwind/dev.css -o /code/static/styles/tw.css -wp"
    tty: true