ARG VARIANT="3.11-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_ROOT_USER_ACTION=ignore
WORKDIR /code
RUN apt-get update \
  && apt-get install -y build-essential curl \
  && curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-arm64 \
  && chmod +x tailwindcss-linux-arm64 \
  && mv tailwindcss-linux-arm64 tailwindcss \
  && mv tailwindcss /usr/bin
COPY ./requirements.txt .
RUN pip install -r requirements.txt