# Generated by Django 3.2.16 on 2022-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blurb', models.CharField(max_length=150)),
                ('explevel', models.CharField(choices=[('exp', 'Expert'), ('pro', 'Proficient'), ('com', 'Competent'), ('adv', 'Advanced Beginner'), ('nov', 'Novice')], default='exp', max_length=3)),
                ('longdesk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=150)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('longdesc', models.TextField()),
                ('repo', models.URLField(blank=True, max_length=2048)),
                ('live', models.URLField(blank=True, max_length=2048)),
                ('promoted', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(to='content.skill')),
            ],
        ),
    ]
