# Generated by Django 3.2.16 on 2022-12-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='longdesk',
            new_name='longdesc',
        ),
    ]
