# Generated by Django 3.2.16 on 2022-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_longdesk_skill_longdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
