# Generated by Django 3.2.16 on 2022-12-13 21:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20221212_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git1', models.URLField(blank=True, max_length=2048)),
                ('git2', models.URLField(blank=True, max_length=2048)),
                ('resumeDL', models.URLField(blank=True, max_length=2048)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
