# Generated by Django 3.2.16 on 2022-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_portfolioowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=50)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('concentration', models.CharField(blank=True, max_length=50)),
                ('achievements', models.TextField(blank=True)),
            ],
        ),
    ]
