# Generated by Django 3.2.16 on 2022-12-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioowner',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
