# Generated by Django 3.2.16 on 2022-12-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_portfolioowner_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioowner',
            name='linkedin',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='portfolioowner',
            name='upwork',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
