# Generated by Django 3.2.16 on 2023-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioowner',
            name='resumeDL',
        ),
        migrations.AddField(
            model_name='portfolioowner',
            name='resume',
            field=models.FileField(blank=True, upload_to='owner_resume/'),
        ),
    ]
