# Generated by Django 3.2.16 on 2023-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20230109_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gradyear',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
