# Generated by Django 3.2.16 on 2023-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_portfolioowner_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioowner',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
