# Generated by Django 3.2.16 on 2023-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_portfolioowner_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioowner',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioowner',
            name='sitename',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
